FROM python:3.9-bullseye
EXPOSE 80

ENV PYTHONUNBUFFERED=TRUE

RUN apt update && apt install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/hedibertosilva/python-api-todos.git \
    && mv python-api-todos /app

WORKDIR /app

RUN pip install .

CMD gunicorn --bind 0.0.0.0:80  wsgi:app --capture-output --enable-stdio-inheritance