version: "3.3"

services:
  api:
    container_name: api-todos
    image: api-todos:1.0
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    ports:
      - mode: host
        published: 5000
        target: 5000
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"